#!/bin/bash
# shellcheck disable=SC1090

# Source dotfiles
for file in ~/.{util,aliases,exports,system,functions}; do
  [ -r "${file}" ] && [ -f "$file" ] && source "${file}"
done
unset file

echo -e "testing"
