#!/bin/bash
# shellcheck disable=SC2034
# shellcheck disable=SC1090


# Bash colors
black=$'\e[0;30m'
red=$'\e[0;31m'
green=$'\e[0;32m'
yellow=$'\e[0;33m'
blue=$'\e[0;34m'
purple=$'\e[0;35m'
cyan=$'\e[0;36m'
white=$'\e[0;37m'
end=$'\e[0m' 

# Function to source dotfiles
function source_dotfile(){
    if test -f "${HOME}/${1}"; then
        source "${HOME}/${1}"
    else
        echo -e "Could not find ${red}${1}${end}"
    fi
}

# Standard coloring
function echo_error() { echo -e "${red}[ERROR] ${1}${end}"; }
function echo_warn() { echo -e "${yellow}[WARNING] ${1}${end}"; }
function echo_ok() { echo -e "${green}[OK] ${1}${end}"; }