repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v0.7.1
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-added-large-files
  - repo: https://github.com/cisagov/pre-commit-shfmt
    rev: v0.0.2
    hooks:
      - id: shfmt
        args:
          - -i
          - '2'

  # - repo: https://github.com/pecigonzalo/pre-commit-shfmt
  #   rev: v2.1.0
  #   hooks:
  #     - id: shell-fmt
