repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v0.7.1
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: check-merge-conflict

  - repo: https://github.com/pecigonzalo/pre-commit-shfmt
    sha: master
    hooks:
      - id: shell-fmt
        args:
          - -i
          - "2"