#!/bin/bash
# shellcheck disable=SC1090
# shellcheck disable=SC1091

# Source dotfiles
for file in ~/.{util,aliases,exports}; do
  [ -r "${file}" ] && [ -f "$file" ] && source "${file}"
done
unset file

source /etc/profile.d/bash_completion.sh

# Terminal colors
PS1='\[\033[1;36m\]\u\[\033[1;31m\]@\[\033[1;32m\]\h:\[\033[1;35m\]\w\[\033[1;31m\]\$\[\033[0m\] '


bind 'set show-all-if-ambiguous on'
bind 'TAB:menu-complete'
