#!/bin/bash
# shellcheck disable=SC1090
# shellcheck disable=SC1091

# Prefer English and UTF-8
export LC_ALL="en_US.UTF-8"
export LANG="en_US.UTF-8"

# Configure ASDF completions
if [[ -d "${ASDF_HOME}" ]]; then
  . "${ASDF_HOME}/asdf.sh"
  if test -f "${ASDF_HOME}/completions/asdf.bash"; then
    . "${ASDF_HOME}/completions/asdf.bash"
  elif test -f "${ASDF_HOME}/etc/bash_completion.d/asdf.bash"; then
    . "${ASDF_HOME}/etc/bash_completion.d/asdf.bash"
  fi
fi
