#!/bin/bash
# shellcheck disable=SC1090
# shellcheck disable=SC1091

# Prefer English and UTF-8
export LC_ALL="en_US.UTF-8"
export LANG="en_US.UTF-8"

# Configure mise completions
if command -v mise &>/dev/null; then
  eval "$(mise activate bash)"
fi
